### ISSUE TITLE
Strange ax behaviour in matplotlib

### ISSUE THREAD

**Issue by aj-daly** [jorisvandenbossche/DS-python-data-analysis#103]
When making a bar plot, I forgot/didn't know to define a second ax object, but I still get the correct output.

Code:

```
unique_species_by_plot = survey_data.groupby(["verbatimLocality"])["name"].nunique()

fig, ax = plt.subplots(figsize=(8,8))
unique_species_by_plot.plot(kind = "barh", color = "pink")
ax.set_ylabel('Plot ID number');
ax.set_xlabel('Number unique species');
```

Output: 
![image](https://user-images.githubusercontent.com/31925903/59030522-88cf4100-8861-11e9-87c3-b6496579cde5.png)

**Comment by stijnvanhoey** [comment]
Thanks for the remark. This is indeed not an issue, both options are valid. As we explain in the `visualization_01_matplotlib.ipynb` notebook, the usage of an additional `ax` object provides more power for customization with matplotlib later on. It is a matter of preference. Hope that helps?
