### ISSUE TITLE
Move to jupyterlab instead of jupyter notebook

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#109]
If we want to switch to jupyterlab instead of jupyter notebook, some things we need to do:

- Update `environment.yml` file
- Update the setup instructions (https://github.com/jorisvandenbossche/DS-python-data-analysis/blob/master/setup.md#3-starting-jupyter-notebook)
- Ensure that everything works in jupyterlab:
    - I think `%matplotlib notebook` does not work

**Comment by stijnvanhoey** [comment]
FIxed by #130, closing this one
