### ISSUE TITLE
FutureWarning when concatenating multiple dataframes

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/DS-python-data-analysis#119]
In notebook `pandas_05_combining_datasets`, when using the `concat` function, the following future warning is provided:

```
FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.
```

During the course, we should use this to explain what a `FutureWarning` actually is. In the future, we can adjust this an translate this to a note.

**Comment by jorisvandenbossche** [comment]
Those warnings are now gone with the latest version of pandas (>= 1.0)
