### ISSUE TITLE
Notes from December 2019 workshop

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#122]
preparation:

- Since previous knowledge of Python is essential to follow the course, send out the information about basic Python earlier than one week in advance, so the students have enough time to go through them and be more prepared.

general:

- [x] replace all isnull/notnull with isna/ notna
- [x] use `dayofweek` instead of `weekday`, which is inconsistent vs Timestamp (method) vs dt/index (property)? (on the other hand, `weekday()` is a datetime.datetime method) 
- [x] put the data in the notebook directory? (for _solved we can use a symlink)

general on titanic:

- [ ] use all lower case names for the columns? (one thing less that you can mistype)
- [ ] use "gender" instead of "sex" ?

pandas_04_timeseries

- [ ] shorten the notebook (only show index?, no partial string? ..)

pandas_06_groupby

>    in pandas_06_groupby_operations.ipynb
>
>    oefening: Add a new column to the cast DataFrame that indicates the number of roles for each movie.
>
>    opmerking: films met Nan rollen worden niet geteld in jullie oplossing.
>
>    ik gebruik:
>
>    cast.merge(cast.groupby(['title']).size().reset_index(name='n_total'), how='left', on='title')
>
>    dan krijg ik voor bvb de film "Gangsta Rap: The Glockumentary" 24 rollen en jullie oplossing geeft Nan

pandas_07_reshape

- [ ] add visual schema for melt (https://twitter.com/justmarkham/status/1206950457677094913) + improve docs
- [ ]  explain first tidy and then melt?
- [ ] is crosstab needed? (do we use it in any of the exercises?)

case1_bike_count:

- [ ] "combined" variable (in the timeit) is never defined or explained
- [ ] "Remove the original "tijd" and "tijd" columns" -> "datum" and "tijd"
- [ ] There are still duplicates in the data, which gives "errors" when checking the daily sums (the first day above 10000 is not in 2013 but in 2012)

Visualization plotnine:

- [x] `dir='v'` is not working any more 

case2_biodiversity_processing:

- [ ] explode -> strip is not needed if you split on " and " instead of "and"
- [ ] the comment about "chained indexing" is not fully correct (any more) + move the copy() call inside the function
- [x] don't overwrite the "backup" (provided) processed data when saving to csv (otherwise if they did something wrong, need to download the data again)

----

Order 2nd day:

- Morning:
  - work on bike count
  - intermezzo: loc/iloc
  - work on bike count
  - before lunch: groupby
- Afternoon
  - matplotlib visualization
  - work on biodiversity
  - reshape
  - plotnine
  - start with bacterial resistance

**Comment by stijnvanhoey** [comment]
tackled in https://github.com/jorisvandenbossche/course-python-data/pull/17 or see https://github.com/jorisvandenbossche/course-python-data/issues/new
