### ISSUE TITLE
A bunch of typos

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#129]
**notebook: case1**

As we finished our data-collection step, we want to save this result as AN interim data output of our small investigation. As such, we do not have to re-download all the files each time something went wrong, but can restart from our interim step.

There are a few records that ARE not exactly 15min. But given it are only a few ones, we will ignore this for the current case study and just keep them as such for this explorative study. Bonus question: do you know where the values of `-1 days +23:15:01` and `01:15:00` are coming from?

2013-06-05 was the first time more than 10,000 bikers passed on one day. Apparanlty, this was not just by coincidence... http://www.nieuwsblad.be/cnt/dmf20130605_022 -> this is not true, the first time was on 2012-10-30. Also, it has to be "Apparently", not "Apparanlty".

**notebook: pandas06_groupby**

Make a bar plot to visualize the average Fare payed by people depending on their age. The age column is DIVIDED IN separate classes using the `pd.cut` function as provided below.

Oftentimes you want to know how many elements there are in a certain group (or in other words: the number of occurences of the different values from a column). -----> First word: pick either 'sometimes' or 'often', but not 'oftentimes'.

Op 3 na laatste oefening: doe groupby niet alleen op 'title', maar ook op 'year': er zijn immers meerdere films met dezelfde titel, die normaal gezien in een ander jaar uitkomen.

**notebook: pandas07_reshaping**

Voorlaatste oefening: voeg in de oplossing een fillna(0) toe, nadat de tabel unstacked is, dan krijg je voor elk jaar een percentage ----> table = grouped.unstack('type').fillna(0)

**notebook: case2_processing**

When explaining the scenario: 'Luckely' should be 'Luckily'

A bit further: occurrenceID: AN identifier ...

To check what the frequency of occurrences is for male/female of the categories, a bar chart is A possible representation

There apparently exists a double entry: `'DM and SH'`, which basically defines two records and should be decoupled to two individual records (i.e. rows). Hence, we should be able to create AN additional row based on this split. To do so, Pandas provides a dedicated function since version 0.25, called `explode`. Starting from a small subset example

The function takes a DataFrame as input, splits the record into separate rows and returns the updated DataFrame. We can use this function to get an update of the dataFrame, with the an additional row (occurrence) added by decoupling the specific field -> delete "the" before the text "an additional row".

The `record_id` is no longer a unique identifier after the decoupling of this dataset. We will make a new dataset-specific identifier, by adding a column called `occurrenceID` that takes a new counter as identifier. As a SIMPLE and straightforward approach, we will use a new counter for the whole dataset, starting with 1

In the survey-dataset we received, the `month`, `day`, and `year` columns are containing the information about the date, i.e. `eventDate` in DarwinCore terms. We want this data in a ISO format `YYYY-MM-DD`. A convenvient Pandas function is the usage of `to_datatime`, which provides multiple options to interpret dates. One of thes options is the automatic interpretation of some 'typical' columns, like `year`, `month` and `day`, when passing a DataFrame. -----> niet 'to_datatime', maar 'to_datEtime'. Ook 'convenient' en niet 'convenVient'

**notebook: case2_analysis**

<b>EXERCISE</b>: Create a table, called <code>heatmap_prep_plotnine</code>, based on the <code>survey_data</code> DataFrame with a column for the years, a column for the months AND a column with the counts (called `count`).

import plotnine as pn -> veranderen naar p9 (voor consistentie). Ook alles in de oplossing van oef. 14 dan aanpassen.

```
# %load _solutions/case2_biodiversity_analysis21.py
species_per_plot = survey_data.reset_index().pivot_table(index="name", 
                                                         columns="verbatimLocality", 
                                                         values="occurrenceID", 
                                                         aggfunc='count')

# alternative ways to calculate this
#species_per_plot =  survey_data.groupby(['name', 'plot_id']).size().unstack(level=-1)
#species_per_plot = pd.crosstab(survey_data['name'], survey_data['plot_id'])			------> change 'plot_id' in alternative solutions to 'verbatimLocality'
```

<b>EXERCISE</b>: What is the number of plots each species have been observed? Make A horizontal bar chart using Pandas `plot` function providing for each species the spread amongst the plots for which the species names are sorted to the number of plots

**Notebook: visualization_03_landscape**

Represent YOUR data [`tidy`](http://www.jeannicholashould.com/tidy-data-in-python.html) to achieve maximal benefit!

**Comment by jorisvandenbossche** [comment]
And we should also check for spell check plugins for jupyter, or check if online services such as grammarly work in the notebook.

**Comment by stijnvanhoey** [comment]
Individual remarks tackled in https://github.com/jorisvandenbossche/DS-python-data-analysis/pull/130 f47d5dcc87cddca278dacce820fd4f9eef489e54
