### ISSUE TITLE
Notes from May/June 2021 workshop

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#144]
Matplotlib:

- [x] Example about putting long code into a function for reuse -> add a docstring!
- [x] Add some actual small exercises on basic matplotlib and matplotlib+pandas!

Seaborn:

- [x] In one of the exercises (eg in bacterial case study), add to the exercise a step where you need to access one of the axes and do a customization with matplotlib (to repeat the link between seaborn and matplotlib in practice)

Visualization landscape:

- `estimator` was not yet used before, should we then use it here?
- Is seaborn also an implementation of grammar of graphics?
- Link to download the Oostende gps data is wrong (it links to acceleration data instead of gps)
- Link to "Bokeh plotting pitfalls datashader" page doesn't exist anymore
- Datashader example can maybe use hvplot instead of holoviews (https://hvplot.holoviz.org/user_guide/Geographic_Data.html#plotting-points)

Reshape:

- [x] title before excercises + re-read titanic data (in case they didn't run all cells above)

Air quality:

- [x] glob glob edit to pathlib

General idea: create case study without reshaping (eg for seaborn you don't need reshape if your data is already tidy), and leave reshape/tidy for third day, while on second day we can already practice groupby and seaborn

---

First day:

- pandas notebooks 1, 2, 3a and 4 (timeseries)
- start with bike count case study

Second day:

- Indexing (3a)
- Groupby
- Combining data
- Start with biodiversity processing case study
- (break)
- Visualization matplotlib
- Continue case study
-

**Comment by stijnvanhoey** [comment]
With respect to 

> Example about putting long code into a function for reuse -> add a docstring!

I dropped the example function as we do not really use it during course and it is not really the best example either.

**Comment by stijnvanhoey** [comment]
cfr.

> estimator was not yet used before, should we then use it here?

I think this is fine, as the main focus here is demonstration purposes.

**Comment by stijnvanhoey** [comment]
closing this one, tackled as part of https://github.com/jorisvandenbossche/course-python-data/pull/17 or in new issue
