### ISSUE TITLE
Python rehearsal - Change all even positions of matrix AR to the value 30

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#152]
If I'm not mistaken, the code below changes all odd positions to 30 (assuming position index starts at 0)

![image](https://user-images.githubusercontent.com/38005924/146748362-690c9fc7-39b8-436d-915a-53afc21a7c23.png)

**Comment by stijnvanhoey** [comment]
This is interesting; is it Python-odd or 'regular'-odd positions?! We should at least make more clear what the purpose is.

**Comment by stijnvanhoey** [comment]
Thanks, I clarified the exercise. tackled in https://github.com/jorisvandenbossche/course-python-data/pull/63
