### ISSUE TITLE
Remark - case_1_bike_count 

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#153]
![image](https://user-images.githubusercontent.com/38005924/146757958-34bd87dd-f6a0-4591-b880-c9d1f5a6a804.png)

I would propose to use the `to_series()` method as this allows for method-chaining (instead of encapsulating in the pd.Series constructor), thus increasing readability

**Comment by stijnvanhoey** [comment]
Indeed. Actually, @jorisvandenbossche, focusing more on method-chaining is worthwhile to check in general as it would increase consistency.

**Comment by jorisvandenbossche** [comment]
Yes, `to_series` is better here (I think our first version of the course predates this method :)) 
Sidenote: pandas should maybe just add a `diff()` method to Index as well.

**Comment by jorisvandenbossche** [comment]
Wanted to open an issue, but apparently there is already one -> https://github.com/pandas-dev/pandas/issues/19708
