### ISSUE TITLE
Remark - case_1_bike_count - power of groupby

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#155]
`df_hourly` is not defined

![image](https://user-images.githubusercontent.com/38005924/146765528-7ffa2320-8246-4e26-a505-9f0bd982619a.png)

should be fixed by inserting a cell above with:
```python
df_hourly = df.resample('H').sum()
```

**Comment by stijnvanhoey** [comment]
Good point, we will update this accordingly
