### ISSUE TITLE
Typo - case2_observation_processing - Exercise 14

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#159]
![image](https://user-images.githubusercontent.com/38005924/146782829-e2d1a2a7-4b83-4214-a558-08c2e84019a9.png)
I suppose `survey_data_plots` should be renamed to `survey_data_decoupled`.

Additionally, sometimes `DataFrames` are written between backticks en sometimes they aren't.

Sorry for the nitpicking 😇

**Comment by stijnvanhoey** [comment]
No worries ;-), it is a valid point on which we should improve the consistency in representing DataFrames/variables, column names and methods. Thanks for the attention for this;
