### ISSUE TITLE
missing answers in pandas_03_selecting_data.ipynb

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [jorisvandenbossche/DS-python-data-analysis#16]
The following two execises do not have the correct answers

<div class="alert alert-success">

<b>EXERCISE</b>:

 <ul>
  <li>Change the capital of the UK to Cambridge</li>
</ul>
</div>

```# %load _solutions/pandas_03_selecting_data41.py
len(titles[titles['year'] // 10 == 195])
```
proposed answer:
```
countries.loc['United Kingdom', 'capital'] = 'Cambridge'
```

<div class="alert alert-success">
<b>EXERCISE</b>:

 <ul>
  <li>Select all countries whose population density is between 100 and 300 people/km²</li>
</ul>
</div>

```
# %load _solutions/pandas_03_selecting_data42.py
inception = cast[cast['title'] == 'Inception']
```
proposed answer:
```
countries[(countries['density'] < 300) & (countries['density'] > 100)]
```

**Comment by stijnvanhoey** [comment]
@jorisvandenbossche needs to be checked when conoverting `_solved` to `notebooks`, as the answers in the original were correct.

**Comment by jorisvandenbossche** [comment]
Yes, we just need to make sure we first do "Run all" before converting the notebooks (or I could actually try to include that in nbtutor), so there are no duplicate execution counts
