### ISSUE TITLE
Bug - case_4_air_quality_processing - Exercise 6

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#166]
![image](https://user-images.githubusercontent.com/38005924/146945355-1ad0de10-36ff-46cf-8682-de543c3b2c21.png)

The `.split` operator is called on a `Path` object

Solution:
* use the `.name` attribute of the Path object to access the last item (also more python to read)
* cast to string and then call split; however, I'm not sure how the path-behavior is in Windows so I would opt for the former.

**Comment by jorisvandenbossche** [comment]
Whoops, we updated it recently to use Pathlib glob instead of `glob.glob`, but didn't check the follow-up code. Thanks for reporting!
