### ISSUE TITLE
Remark - case4_air_quality_analysis - Just above Exercise 6

### ISSUE THREAD

**Issue by jonasvdd** [jorisvandenbossche/DS-python-data-analysis#167]
The code blocks (defined with `<code>` do not render that nicely:

![image](https://user-images.githubusercontent.com/38005924/146956281-b1d72fc3-d830-4108-83b8-576cae7ddd1c.png)

I would suggest changing it into triple backticks, which looks like this:

![image](https://user-images.githubusercontent.com/38005924/146956788-63afb121-853e-484e-a6d6-87226b503767.png)

**Comment by jorisvandenbossche** [comment]
Yes, thanks, that's still some left-over from the time that the notebook didn't support backticks in such boxes
