### ISSUE TITLE
incorrect solutions

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [jorisvandenbossche/DS-python-data-analysis#21]
<div class="alert alert-success">

<b>EXERCISE</b>:

 <ul>
  <li>Using groupby(), calculate the average age for each sex.</li>
</ul>
</div>

given answer:

```
# %load _solutions/pandas_06_groupby_operations10.py
df25 = df[df['Age'] <= 25]
df25['Survived'].sum() / len(df25['Survived'])
```

proposed answer:
```
df.groupby('Sex')['Age'].aggregate(np.mean)
```

**Comment by DaanVanHauwermeiren** [comment]
<div class="alert alert-success">

<b>EXERCISE</b>:

 <ul>
  <li>Calculate the average survival ratio for all passengers.</li>
</ul>
</div>

should be:

<div class="alert alert-success">

<b>EXERCISE</b>:

 <ul>
  <li>Calculate the average survival ratio for all passengers, grouped by sex</li>
</ul>
</div>

**Comment by cdemulde** [comment]
**EXERCISE**

- What is the difference in the survival ratio between the sexes?

given answer
`df.groupby('Sex')['Survived'].mean()`

proposed answer
`df_grouped = df.groupby('Sex')`
`df_grouped['Survived'].sum()/df_grouped['Survived'].size()`

**Comment by stijnvanhoey** [comment]
Apart from the proposal of @cdemulde, which is just an equivalent solution (calculating the ration itself instead of using the mean), this is a similar problem as #16, with the answers written to wrong files. Closing here...
