### ISSUE TITLE
Collection of errors / suggestions

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/DS-python-data-analysis#23]
@jorisvandenbossche talking:

- [x] matplotlib notebook: example of fig vs ax -> 'ax' -> 'ax1'
- [x] autofmt_xdate -> can take rotation keyword!
- [x] bike data -> drop_duplicates:
  -  can also use index.duplicated
  - or for drop_duplicates -> use subset to drop based on the datetimes

**Comment by jorisvandenbossche** [comment]
- overzicht cheatsheet figuur : hline/vline

**Comment by jorisvandenbossche** [comment]
* numpy recap: `reshape` nodig?
* pandas_03_indexing -> eerste exercise (density): not using bootstrap format
* resample: remove note about older versions
* biodiversity: occurrenceId columns -> bemerken dat 'reset_index(drop=True)' ook werkt, maar hier `df.index = np.arange(1,..)` omdat we willen dat start bij één

notes from @stijnvanhoey (you can clarify if I didn't read it correctly)

* air quality processing:
  * concat:
    *`pd.concat([])` -> [] from the for loop (clarify!)
    * vb toevoegen voor dict `{}` gebruik in concat
  * end of the notebook -> link to file / main (is this the workflow notebook?)
* exercise sorted air quality: ?


varia:

* ipython greedy completion?

**Comment by stijnvanhoey** [comment]
* `%whos` -> list of variable in current namespace

**Comment by stijnvanhoey** [comment]
With respect to the `drop_duplicates` action in the bike count data; this should refer to an alternative of 
`df3 = df3.reset_index().drop_duplicates().set_index("index")` : shoud the comparison actually take the entire row into account? Or should we just check the datetime-index? 

The latter as solution would indeed make a shorter version possible, e.g. `df3[~df3.index.duplicated()].info()`. However the result contains 1 record less compared to the entire row comparison.

**Comment by jorisvandenbossche** [comment]
The difference is apparently on only dropping based on the index:

```
>>> df3.reset_index().drop_duplicates().set_index("index").shape
(91831, 3)

>>> df3.reset_index().drop_duplicates(subset=['index']).set_index("index").shape
(91830, 3)
```

and that is due to a difference in the active column:

```
>>> df3[df3.index.duplicated(keep=False)].head()
  | north | south | active
-- | -- | -- | --
1 | 9 | NaN
1 | 9 | OFF
10 | 10 | NaN
7 | 15 | NaN
14 | 15 | NaN
```

so only dropping based on the index is more correct anyway

**Comment by stijnvanhoey** [comment]
But on the other hand, with only using the `index`, you will not be aware of the differnece in `active` for the 2013-11-21 03:40:23 timestamp...

**Comment by stijnvanhoey** [comment]
with respect to numpy recap: `reshape` nodig? -> reshape is present in the notebook.

**Comment by jorisvandenbossche** [comment]
> with respect to numpy recap: reshape nodig? -> reshape is present in the notebook.

Do we use reshape somewhere in the case studies / pandas notebooks?

**Comment by stijnvanhoey** [comment]
We should check while rechecking the notebooks...

**Comment by stijnvanhoey** [comment]
Dus to the new data provided by city of Ghent, we can not use the `drop_duplicates` exercise anymore, removing the issue as well.
