### ISSUE TITLE
More efficient solution for python_rehearsal119.py

### ISSUE THREAD

**Issue by FemkeBatsleer** [jorisvandenbossche/DS-python-data-analysis#49]
Found a much faster solution for python_rehearsal119.py:

%%timeit
**np.count_nonzero(AR>10)**
1.44 µs ± 90.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

Instead of:
%%timeit
sum(AR>10)
45.2 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%%timeit
np.sum(AR>10)
4.66 µs ± 830 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

**Comment by jorisvandenbossche** [comment]
@FemkeBatsleer Thanks for the feedback! 
We are updating the materials for the workshop version of this year now, so going through the issues :)

For this specific one, it is indeed true that `np.count_nonzero` will be more efficient than `np.sum` in case of boolean values. However, it's also a trade-off with simplicity, and `np.sum` is already a function we see and use regularly throughout the course, so I think I would keep it on that (we could maybe still add a note mentioning `np.count_nonzero`).

**Comment by stijnvanhoey** [comment]
As in the latest version of the course, this is not part of the notebook anymore, I'm closing this issue.
