### ISSUE TITLE
Some small typos 

### ISSUE THREAD

**Issue by MarliesDeClercq** [jorisvandenbossche/DS-python-data-analysis#50]
01-basic.ipynb

test out the **nxt** two lines one at a time --> next
If **their** not yet a string --> they are

02-control_flow.ipynb

Different exceptions can be combined, **rasingin** different type of errors --> raising

03-functions.ipynb

It is just the same **al** all the other objects we worked with! --> as

05-numpy.ipynb

We use matplotlib to **sho** histogram --> show

python_rehearsal.ipynb

eerst 'builtin', wat later 'built-in'

**Comment by stijnvanhoey** [comment]
thanks!
