### ISSUE TITLE
case3 bacterial resistance: variable median/mean 

### ISSUE THREAD

**Issue by nelerey** [jorisvandenbossche/DS-python-data-analysis#60]
Exercise on optical density: create density_mean: 

In the assignment:
Calculate for each combination of Bacterial_genotype, Phage_t and experiment_time_h the mean optical_density and store the result as a dataframe called density_mean
==> mean of optical density is asked

In your solution:
density_mean = (tidy_experiment
                .groupby(['Bacterial_genotype','Phage_t', 'experiment_time_h'])
                .median().reset_index())
==> median optical density and survival are given

**Comment by stijnvanhoey** [comment]
Thanks for reporting, solution adapted.
