### ISSUE TITLE
rendering of html exercise sections not properly displayed

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#75]
Due to increase in TAB, the list is interpreted as pure code and not properly rendered

**Comment by jorisvandenbossche** [comment]
Simple fix: blank space (https://github.com/jupyter/notebook/issues/4504)

**Comment by SimonMichels** [comment]
I have the same issue in notebook pandas_01_data_structures
Code: <div class="alert alert-success">
    <b>EXERCISE</b>:

    <ul>
        <li>How many records (i.e. rows) has the titanic dataset?</li>
    </ul>
</div>

**Comment by lcdvissc** [comment]
Coloured boxes don't work in Jupyterlab.

**Comment by jorisvandenbossche** [comment]
> Coloured boxes don't work in Jupyterlab.

They are now in the latest version (see https://github.com/jupyterlab/jupyterlab/pull/5621), but this version is not yet packages by conda-forge or Anaconda, so hopefully next course it will be.

**Comment by stijnvanhoey** [comment]
we can close this issue, as this currently works in Jupyter lab
