### ISSUE TITLE
SHIFT+TAB instead of CTRL+TAB

### ISSUE THREAD

**Issue by pedroxramos** [jorisvandenbossche/DS-python-data-analysis#82]
In notebook "case2_biodiversity_processing
(autosaved)", instead of

" # get help of the function by CTRL + TAB"

should be 

" # get help of the function by SHIFT + TAB"

<img width="599" alt="screenshot 2018-12-04 at 13 48 17" src="https://user-images.githubusercontent.com/45520407/49442947-49993800-f7cb-11e8-9886-9c7df2775fff.png">

**Comment by jorisvandenbossche** [comment]
Thanks for the issue! We will make sure to fix this for the next edition.

**Comment by jorisvandenbossche** [comment]
Fixed in https://github.com/jorisvandenbossche/DS-python-data-analysis/pull/88
