### ISSUE TITLE
Show months as discrete integers in heatmap plotnine

### ISSUE THREAD

**Issue by YBawin** [jorisvandenbossche/DS-python-data-analysis#84]
In the case2_biodiversity_analysis notebook, the months on the x-axis of the plotnine heatmap are shown as continuous values (i.e. 0, 2.5, 5, ... ). It would be nice if they are shown as discrete values in the solution (i.e 1, 2, 3, ...) by setting the x-labels as a factor.

**Comment by jorisvandenbossche** [comment]
Fixed in https://github.com/jorisvandenbossche/DS-python-data-analysis/pull/88
