### ISSUE TITLE
typo python_recap/01-basic

### ISSUE THREAD

**Issue by lcdvissc** [jorisvandenbossche/DS-python-data-analysis#92]
**Exercise**: With the `dir(list)` command, all the methods of the list type are printed. However, **_where_** ... -> we're

**Comment by stijnvanhoey** [comment]
Well spotted, thanks! Fixed by https://github.com/jorisvandenbossche/DS-python-data-analysis/commit/5e06ade46f368e14118034a40c9f390e8e5517e3
