### ISSUE TITLE
typo in pandas_04_time_series_data.ipynb notebook

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/DS-python-data-analysis#93]
`s = pd.Series(['2016-12-09 10:00:00', '2016-12-09, 11:00:00', '2016-12-09 12:00:00'])` has a redundant `,`

**Comment by lcdvissc** [comment]
We have **to** much data to sensibly plot on one figure. -> We have **too** much data to sensibly plot on one figure.

**Comment by stijnvanhoey** [comment]
thanks!

**Comment by SimonMichels** [comment]
"The plot method will also adapt it's labels" --> should be "its" labels

**Comment by stijnvanhoey** [comment]
thanks, adjusted in b68264064573605596bde8dfed8344d32546a0a1
