### ISSUE TITLE
Notes from June 2019 workshop

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/DS-python-data-analysis#97]
General:

- first morning: mention that people need to download latest version of the material (idea: tag to make a release before the course)
- is `%matplotlib inline` still needed?

Slides:
- [x] update conda page (environment, source activate -> activate, ..)
- [x] Ipython -> IPython
- [x] IDE's update with Atom / VSCode

Pandas 1:
- [x] column names in overview table titanic wrong
- [x] no .values for dataframe
- [x] html boxen

Pandas 3 selecting:
- [x] `and` -> `&` to combine conditions => add tip for this

Pandas 3b indexing:

- [x]  update setting with copy warning section with more explanation (temporary variable, boolean selection on population, show both and that the one does not work `countries.loc[countries['population'] > 50, 'population'] = 50`)

Pandas 4:

* [ ] Ways to shorten this a bit?

Pandas 6 - groupby:

* [x] The `color=C0` in the last exercise is not needed anymore

pandas 7 reshape:

- [x] last exercise pivot_table mean -> median

Visualization - plotnine:

- [x] the `by` in the first pandas example not doing anything?

Visualization - landscape:

- [x] update: Bokeh now supports pdf

Case 1 - bike count:

- [x] have raw data as backup

Case 2 - biodiversity processing:

- [x] groupby doesn't count NaNs, value_counts does -> add a note to explain that difference?

Case 2 - biodiversity analysis:

- [x] don't use built-in sum
- [x] subselection_sex -> make subtask to create this variable

Case 3 bacterial resistance:

- [x] intial tidying: we loose the "experiment id" or "repetion id" in the original data (multiple repeptitions for same phage / genotype, which now is a single row) -> that information is lost
- [x] creation of `density_mean` -> select column 'optical_density' before `.mean()` -> no mean of survival etc .. (in solution)

**Comment by stijnvanhoey** [comment]
+ update pandas logo in slides

**Comment by stijnvanhoey** [comment]
@jorisvandenbossche can we close this issue and maybe move the remaining question to a separate issue?
