### ISSUE TITLE
Typo in case2_biodiversity_processing

### ISSUE THREAD

**Issue by lcdvissc** [jorisvandenbossche/DS-python-data-analysis#98]
(text after `solve_double_field_entry`)

The function takes a DataFrame as input, splits the record into separate rows and **returnd** ... -> **returns**

**Comment by lcdvissc** [comment]
(OPTIONAL SECTION)

... different species in our dataset would be useful to integrate our work with other research. An option is to **mathc** ...-> **match**

**Comment by lcdvissc** [comment]
.... The main library we need to this kind of automated searches is the **request** package -> **requests**

**Comment by SimonMichels** [comment]
Above line [29], in the exercise, the function drop_na() is advised. But the right function is dropna()

**Comment by stijnvanhoey** [comment]
Thanks for al these, tackled in b507739d28542298e2996f3768bf3a5dde712423
